#!/bin/bash
#
# 'install'
#
# install is run at the beginning of a charm lifecycle.
# The hook should be used to perform one-time setup operations,
# such as installing prerequisite software that will not change
# with configuration changes.
# Like all hooks this must be idempotent because there are scenarios
# where this hook can be run more than once.
#

status-set maintenance 'Installed, waiting for start'

juju-log -l 'INFO' 'Did some installing'
