#!/bin/bash
set -eu

remote_host=`relation-get private-address`
export_path=`relation-get mountpoint`
mount_options=`relation-get options`
fstype=`relation-get fstype`

if [ -z "${export_path}" ]; then
    juju-log "remote host not ready"
    exit 0
fi

local_mountpoint="/var/lib/tiny"
docroot="/var/www/tiny"

create_local_mountpoint() {
  juju-log "creating local mountpoint"
  umask 022
  mkdir -p $local_mountpoint
  chown -R www-data:www-data $local_mountpoint
}
[ -d "${local_mountpoint}" ] || create_local_mountpoint

share_already_mounted() {
  `mount | grep -q $local_mountpoint`
}

mount_share() {
  for try in {1..3}; do
    juju-log "mounting share"
    [ ! -z "${mount_options}" ] && options="-o ${mount_options}" || options=""
    mount  -t $fstype $options $remote_host:$export_path $local_mountpoint \
      && break

    juju-log "mount failed: ${local_mountpoint}"
    sleep 10

  done
}

apt-get -qqy install rpcbind nfs-common rsync

# migrate data and symlink
migrate_data () {
  if [ ! -L $docroot ]; then
	rsync -az $docroot/* $local_mountpoint
	mv $docroot /mnt/owncloud-backup
	ln -s $local_mountpoint $docroot
  fi
}

share_already_mounted || mount_share

if [ share_already_mounted ]; then
  juju-log "Will not migrate data: ${local_mountpoint}"
  # migrate_data
fi
