#!/bin/bash
#
# 'start'
#
# start runs immediately after the first config-changed hook.
# It should be used to ensure the charm's software is running.
# Note that the charm's software should be configured so as to
# persist through reboots without further intervention on juju's part.

status-set active 'Started tiny-bash'
