#!/bin/bash
#
# 'update-status'
#
# Provides constant feedback to the user about the status
# of the service the charm is modeling.
# The charm is run by Juju at regular intervals,
# and gives authors an opportunity to run code that gets
# the “health” of the service or services.

juju-log -l 'INFO' 'update-status ran'
status-set active "update-status ran: $(date +"%H:%M")"
